name: "jest-reports"
branding:
  icon: "umbrella"
  color: "blue"
description: "test coverage reporter"
author: "vgrafe"
inputs:
  github-token:
    description: "A github access token"
    default: ${{ github.token }}
  cover-changes-only:
    description: "True if tests must be run only for changes in the PR"
    default: False
  coverage-annotations:
    description: "Add aggregated coverage annotations. Default to 'changes-only'. Other values are 'none' and 'all'"
    default: "changes-only"
runs:
  using: composite
  steps:
    # forcing node 16.10.0 since later versions have memory issues with jest
    - uses: actions/setup-node@v3
      with:
        node-version: "16.10.0"

    # needed for cache to work https://github.com/crazy-max/ghaction-github-runtime
    - name: Expose GitHub Runtime
      uses: crazy-max/ghaction-github-runtime@v2

    - run: INPUT_COVERAGE_ANNOTATIONS=${{ inputs.coverage-annotations }} INPUT_GITHUB_TOKEN=${{ inputs.github-token }} INPUT_COVER_CHANGES_ONLY=${{ inputs.cover-changes-only }} node ${{ github.action_path }}/dist/index.js
      shell: bash
