name: "Couette - jest cov report"
# description: "Provide a description here"
author: "vgrafe"
inputs:
  github-token:
    description: "A github access token"
    default: ${{ github.token }}
runs:
  steps:
    - run: $GITHUB_ACTION_PATH/run.sh
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
