name: jest-reports
on: [pull_request]

jobs:
  compare-cov:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: vgrafe/jest-reports@v0.111
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
